"""Membuat semua tabel dari awal

Revision ID: 52734bbe396a
Revises: 
Create Date: 2025-06-24 10:10:57.578757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52734bbe396a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('spesialis', sa.String(length=100), nullable=True),
    sa.Column('spesialis_level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('sertifikat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sertifikat', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spesialis', sa.String(length=100), nullable=False),
    sa.Column('spesialis_level', sa.String(length=50), nullable=True),
    sa.Column('tanggal_terbit', sa.Date(), nullable=False),
    sa.Column('penandatangan', sa.String(length=100), nullable=False),
    sa.Column('signature_hash', sa.String(length=256), nullable=True),
    sa.Column('qr_code_img', sa.LargeBinary(), nullable=True),
    sa.Column('tanggal_sign', sa.DateTime(), nullable=True),
    sa.Column('data_string_untuk_sign', sa.Text(), nullable=True),
    sa.Column('pdf_file_path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sertifikat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sertifikat')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
