"""Initial database schema for new environment

Revision ID: ade9c5d0888f
Revises: 
Create Date: 2025-06-02 14:42:25.516372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade9c5d0888f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('spesialis', sa.String(length=50), nullable=True),
    sa.Column('spesialis_level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sertifikat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id_sertifikat', sa.String(length=100), nullable=False),
    sa.Column('spesialis', sa.String(length=200), nullable=False),
    sa.Column('tanggal_terbit', sa.Date(), nullable=False),
    sa.Column('nama_lembaga_penerbit', sa.String(length=150), nullable=False),
    sa.Column('data_string_untuk_sign', sa.Text(), nullable=True),
    sa.Column('signature_hash', sa.Text(), nullable=True),
    sa.Column('tanggal_sign', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sertifikat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sertifikat')
    op.drop_table('user')
    # ### end Alembic commands ###
