"""Add pdf_file_hash to Sertifikat

Revision ID: b4afc0e0c137
Revises: c778c66e719c
Create Date: 2025-06-22 20:38:46.481944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4afc0e0c137'
down_revision = 'c778c66e719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sertifikat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_sertifikat_pdf_file_hash'), ['pdf_file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sertifikat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sertifikat_pdf_file_hash'))
        batch_op.drop_column('pdf_file_hash')

    # ### end Alembic commands ###
