"""Add pdf_file_path to Sertifikat model

Revision ID: c778c66e719c
Revises: ade9c5d0888f
Create Date: 2025-06-19 13:02:48.084552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c778c66e719c'
down_revision = 'ade9c5d0888f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sertifikat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file_path', sa.String(length=300), nullable=True))
        batch_op.alter_column('spesialis',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('penandatangan',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('signature_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sertifikat', schema=None) as batch_op:
        batch_op.alter_column('signature_hash',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('penandatangan',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('spesialis',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('pdf_file_path')

    # ### end Alembic commands ###
