"""Add pdf_file_hash to Sertifikat

Revision ID: cbf1ab9dfc88
Revises: 52734bbe396a
Create Date: 2025-06-25 19:31:57.960726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf1ab9dfc88'
down_revision = '52734bbe396a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sertifikat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file_hash', sa.String(length=256), nullable=True))
        batch_op.drop_column('spesialis_level')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('spesialis_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spesialis_level', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('sertifikat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spesialis_level', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('pdf_file_hash')

    # ### end Alembic commands ###
